// matodef.h

#ifndef def
#define def

// Include files

#include <stdlib.h>
#include <conio.h>
#include <iostream.h>
#include <dos.h>

// Keys

#define LARROW  1075
#define RARROW  1077
#define UARROW  1072
#define DARROW  1080
#define QUIT    27

// Screen size

#define WIDTH 	40
#define HEIGHT  25

// Graphic characters

#define HEAD    1
#define BODY    219
#define WALL    178

// Directions

#define UP			0
#define	RIGHT		1
#define	DOWN		2
#define	LEFT		3

// Colors

#define BODYCOLOR	YELLOW
#define HEADCOLOR	YELLOW
#define WALLCOLOR	BLUE
#define BKCOLOR		BLACK
#define FOODCOLOR GREEN

#endif